#!/bin/sh
# .git/hooks/commit-msg
. "$(dirname "$0")/_/husky.sh"
# npx husky add .husky/commit-msg 'npx commitlint --edit $1'
echo 'the commit-msg hook started'
npx --no-install commitlint --edit $1
echo 'the commit-msg hook is done'
exit 0;
