#!/bin/sh
. "$(dirname "$0")/_/husky.sh"
# npx husky add .husky/commit-msg 'npx commitlint --edit $1'
# npx --no-install commitlint --edit $1
# npx pretty-quick --staged
echo 'the pre-push hook started'
npm run lint 
echo 'the pre-push hook is done'
exit 0
